apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana-datasource
  namespace: default
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: default
    kubectl.kubernetes.io/last-applied-configuration: ""
  creationTimestamp: "2022-06-01T09:41:18Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 35.2.0
    chart: kube-prometheus-stack-35.2.0
    grafana_datasource: "1"
    heritage: Helm
    release: kube-prometheus-stack
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090/
      jsonData:
        exemplarTraceIdDestinations:
          - name: trace_id
            url: http://localhost:16686/trace/$${__value.raw}