apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemplar-demo
  namespace: default
  labels:
    app: exemplar-demo
spec:
  selector:
    matchLabels:
      app: exemplar-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: exemplar-demo
    spec:
      containers:
        - name: exemplar-demo
          image: exemplar-demo:latest
          imagePullPolicy: Never
          ports:
            - name: web
              containerPort: 8080