management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  application:
    name: exemplar-demo
  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://simplest-collector.default.svc.cluster.local:4317
      config:
        trace-id-ratio-based: 1.0